// Code generated by Slice Machine. DO NOT EDIT.

import NotFound from './NotFound.svelte';
import HeroSlice from './HeroSlice.svelte';
import RichTextSlice from './RichTextSlice.svelte';
import ImageSlice from './ImageSlice.svelte';
import ReviewsSlice from './ReviewsSlice.svelte';
import HeadingSlice from './HeadingSlice.svelte';
import FeatureSlice from './FeatureSlice.svelte';
import CarouselSlice from './CarouselSlice.svelte';
import JobSlice from './JobSlice.svelte';
import FAQSlice from './FAQSlice.svelte';
import InfoSectionSlice from './InfoSectionSlice.svelte';
import TransportSlice from './TransportSlice.svelte';
import CheckInSlice from './CheckInSlice.svelte';
import MapSlice from './MapSlice.svelte';
import ContactSlice from './ContactSlice.svelte';

export const components = {
  hero_slice: HeroSlice,
  rich_text: RichTextSlice,
  image_slice: ImageSlice,
  reviews_slice: ReviewsSlice,
  heading_slice: HeadingSlice,
  feature_slice: FeatureSlice,
  carousel_slice: CarouselSlice,
  job_slice: JobSlice,
  faq_slice: FAQSlice,
  info_section: InfoSectionSlice,
  transport_slice: TransportSlice,
  checkin_slice: CheckInSlice,
  map_slice: MapSlice,
  contact_slice: ContactSlice,
};

export { NotFound };
