// Code generated by Slice Machine. DO NOT EDIT.

import NotFound from './NotFound.svelte';
import HeroSlice from './HeroSlice.svelte';
import RichTextSlice from './RichTextSlice.svelte';
import ImageSlice from './ImageSlice.svelte';
import ReviewsSlice from './ReviewsSlice.svelte';
import HeadingSlice from './HeadingSlice.svelte';
import FeatureSlice from './FeatureSlice.svelte';

export const components = {
  hero_slice: HeroSlice,
  rich_text: RichTextSlice,
  image_slice: ImageSlice,
  reviews_slice: ReviewsSlice,
  heading_slice: HeadingSlice,
  feature_slice: FeatureSlice,
};

export { NotFound };
