// Code generated by Slice Machine. DO NOT EDIT.

import NotFound from './NotFound.svelte';
import HeroSlice from './HeroSlice.svelte';
import RichTextSlice from './RichTextSlice.svelte';
import ImageSlice from './ImageSlice.svelte';
import ReviewsSlice from './ReviewsSlice.svelte';
import HeadingSlice from './HeadingSlice.svelte';
import FeatureSlice from './FeatureSlice.svelte';
import CarouselSlice from './CarouselSlice.svelte';
import JobSlice from './JobSlice.svelte';
import FAQSlice from './FAQSlice.svelte';
import RoomsSlice from './rooms_slice/index.svelte';

export const components = {
  hero_slice: HeroSlice,
  rich_text: RichTextSlice,
  image_slice: ImageSlice,
  reviews_slice: ReviewsSlice,
  heading_slice: HeadingSlice,
  feature_slice: FeatureSlice,
  carousel_slice: CarouselSlice,
  job_slice: JobSlice,
  faq_slice: FAQSlice,
  rooms_slice: RoomsSlice,
};

export { NotFound };
