// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Contact Information documents
 */
interface ContactInfoDocumentData {
  /**
   * Hotel Name field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hotel Ludwig van Beethoven
   * - **API ID Path**: contact_info.hotel_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hotel_name: prismic.KeyTextField;

  /**
   * Main Phone Number field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +49 30 695 066 0
   * - **API ID Path**: contact_info.phone_main
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone_main: prismic.KeyTextField;

  /**
   * Phone Display Format field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +49 30 695 066 0
   * - **API ID Path**: contact_info.phone_display
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone_display: prismic.KeyTextField;

  /**
   * Main Email field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: info@hotel-ludwig-van-beethoven.de
   * - **API ID Path**: contact_info.email_main
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_main: prismic.KeyTextField;

  /**
   * Jobs Email (German) field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: bewerbung@hotel-ludwig-van-beethoven.de
   * - **API ID Path**: contact_info.email_jobs
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_jobs: prismic.KeyTextField;

  /**
   * Jobs Email (English) field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: jobs@hotel-ludwig-van-beethoven.de
   * - **API ID Path**: contact_info.email_jobs_en
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_jobs_en: prismic.KeyTextField;

  /**
   * Street Address field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hasenheide 14
   * - **API ID Path**: contact_info.address_street
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address_street: prismic.KeyTextField;

  /**
   * City and Postal Code field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 10967 Berlin
   * - **API ID Path**: contact_info.address_city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address_city: prismic.KeyTextField;

  /**
   * Country (German) field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Deutschland
   * - **API ID Path**: contact_info.address_country_de
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address_country_de: prismic.KeyTextField;

  /**
   * Country (English) field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Germany
   * - **API ID Path**: contact_info.address_country_en
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address_country_en: prismic.KeyTextField;

  /**
   * Website URL field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://hotel-ludwig-van-beethoven.de
   * - **API ID Path**: contact_info.website_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  website_url: prismic.KeyTextField;

  /**
   * Reception Hours (German) field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 24 Stunden geöffnet
   * - **API ID Path**: contact_info.reception_hours_de
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  reception_hours_de: prismic.KeyTextField;

  /**
   * Reception Hours (English) field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Open 24 hours
   * - **API ID Path**: contact_info.reception_hours_en
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  reception_hours_en: prismic.KeyTextField;

  /**
   * Phone Availability (German) field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Täglich 24 Stunden erreichbar
   * - **API ID Path**: contact_info.phone_available_de
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone_available_de: prismic.KeyTextField;

  /**
   * Phone Availability (English) field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Available 24 hours daily
   * - **API ID Path**: contact_info.phone_available_en
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone_available_en: prismic.KeyTextField;

  /**
   * Email Response Time (German) field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Wir antworten innerhalb von 24 Stunden
   * - **API ID Path**: contact_info.email_response_de
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_response_de: prismic.KeyTextField;

  /**
   * Email Response Time (English) field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: We respond within 24 hours
   * - **API ID Path**: contact_info.email_response_en
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_response_en: prismic.KeyTextField /**
   * Meta Title field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact Information for Hotel Ludwig van Beethoven
   * - **API ID Path**: contact_info.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Centralized contact information for Hotel Ludwig van Beethoven
   * - **API ID Path**: contact_info.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Contact Information document from Prismic
 *
 * - **API ID**: `contact_info`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactInfoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactInfoDocumentData>,
    "contact_info",
    Lang
  >;

/**
 * Content for FAQ Item documents
 */
interface FaqItemDocumentData {
  /**
   * Question field in *FAQ Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Wann sind die Check-in und Check-out Zeiten?
   * - **API ID Path**: faq_item.question
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FAQ Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the answer to this question...
   * - **API ID Path**: faq_item.answer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;

  /**
   * Category field in *FAQ Item*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select category
   * - **API ID Path**: faq_item.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    "Allgemein" | "Anreise" | "Ausstattung" | "Service" | "Buchung"
  >;

  /**
   * Display Order field in *FAQ Item*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1
   * - **API ID Path**: faq_item.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  order: prismic.NumberField;

  /**
   * Featured FAQ field in *FAQ Item*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: faq_item.is_featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_featured: prismic.BooleanField /**
   * Meta Title field in *FAQ Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO title for this FAQ
   * - **API ID Path**: faq_item.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *FAQ Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO description for this FAQ
   * - **API ID Path**: faq_item.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * FAQ Item document from Prismic
 *
 * - **API ID**: `faq_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqItemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FaqItemDocumentData>,
    "faq_item",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | HeroSliceSlice
  | RichTextSlice
  | ImageSliceSlice
  | ReviewsSliceSlice
  | HeadingSliceSlice
  | FeatureSliceSlice
  | CarouselSliceSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief description of this page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Job Listing documents
 */
interface JobListingDocumentData {
  /**
   * Job Title field in *Job Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Rezeptionist/in
   * - **API ID Path**: job_listing.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Department field in *Job Listing*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select department
   * - **API ID Path**: job_listing.department
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  department: prismic.SelectField<
    "Front Office" | "Housekeeping" | "Service" | "Kitchen" | "Management"
  >;

  /**
   * Job Type field in *Job Listing*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select job type
   * - **API ID Path**: job_listing.job_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  job_type: prismic.SelectField<
    "Vollzeit" | "Teilzeit" | "Minijob" | "Praktikum"
  >;

  /**
   * Job Description field in *Job Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the job description...
   * - **API ID Path**: job_listing.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Responsibilities field in *Job Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: List job responsibilities...
   * - **API ID Path**: job_listing.responsibilities
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  responsibilities: prismic.RichTextField;

  /**
   * Requirements field in *Job Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: List job requirements...
   * - **API ID Path**: job_listing.requirements
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  requirements: prismic.RichTextField;

  /**
   * Benefits field in *Job Listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: List job benefits...
   * - **API ID Path**: job_listing.benefits
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  benefits: prismic.RichTextField;

  /**
   * Contact Email field in *Job Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: bewerbung@hotel-ludwig-van-beethoven.de
   * - **API ID Path**: job_listing.contact_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Job Active field in *Job Listing*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: job_listing.is_active
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_active: prismic.BooleanField /**
   * Meta Title field in *Job Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO title for this job listing
   * - **API ID Path**: job_listing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Job Listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO description for this job listing
   * - **API ID Path**: job_listing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Job Listing document from Prismic
 *
 * - **API ID**: `job_listing`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobListingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<JobListingDocumentData>,
    "job_listing",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | HeroSliceSlice
  | RichTextSlice
  | ImageSliceSlice
  | ReviewsSliceSlice
  | HeadingSliceSlice
  | FeatureSliceSlice
  | CarouselSliceSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Page Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Page title
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief description of this page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | ContactInfoDocument
  | FaqItemDocument
  | HomepageDocument
  | JobListingDocument
  | PageDocument;

/**
 * Primary content in *CarouselSlice → Default → Primary*
 */
export interface CarouselSliceSliceDefaultPrimary {
  /**
   * Section Heading field in *CarouselSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter section heading...
   * - **API ID Path**: carousel_slice.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Section Subheading field in *CarouselSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter section subheading...
   * - **API ID Path**: carousel_slice.default.primary.section_subheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subheading: prismic.RichTextField;

  /**
   * Section Description field in *CarouselSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description...
   * - **API ID Path**: carousel_slice.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Aspect Ratio field in *CarouselSlice → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose aspect ratio
   * - **Default Value**: 16/9
   * - **API ID Path**: carousel_slice.default.primary.aspect_ratio
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  aspect_ratio: prismic.SelectField<
    "16/9" | "21/9" | "4/3" | "3/2" | "1/1",
    "filled"
  >;

  /**
   * Autoplay field in *CarouselSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carousel_slice.default.primary.autoplay
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  autoplay: prismic.BooleanField;

  /**
   * Autoplay Interval (ms) field in *CarouselSlice → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 5000
   * - **API ID Path**: carousel_slice.default.primary.autoplay_interval
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  autoplay_interval: prismic.NumberField;

  /**
   * Show Preview Thumbnails field in *CarouselSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: carousel_slice.default.primary.show_thumbnails
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_thumbnails: prismic.BooleanField;

  /**
   * Show Dot Indicators field in *CarouselSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: carousel_slice.default.primary.show_indicators
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_indicators: prismic.BooleanField;

  /**
   * Show Navigation Arrows field in *CarouselSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: carousel_slice.default.primary.show_navigation
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_navigation: prismic.BooleanField;
}

/**
 * Primary content in *CarouselSlice → Items*
 */
export interface CarouselSliceSliceDefaultItem {
  /**
   * Carousel Image field in *CarouselSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<"carousel_thumb">;

  /**
   * Image Caption field in *CarouselSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter image caption...
   * - **API ID Path**: carousel_slice.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Room Title field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Einzelzimmer
   * - **API ID Path**: carousel_slice.items[].room_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  room_title: prismic.KeyTextField;

  /**
   * Room Description field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Perfekt für Alleinreisende
   * - **API ID Path**: carousel_slice.items[].room_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  room_description: prismic.KeyTextField;

  /**
   * Bed Type field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Einzelbett mit Federkernmatratze
   * - **API ID Path**: carousel_slice.items[].room_bed_type
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  room_bed_type: prismic.KeyTextField;

  /**
   * Booking Button Text field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Jetzt Buchen
   * - **API ID Path**: carousel_slice.items[].booking_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  booking_button_text: prismic.KeyTextField;

  /**
   * Booking URL field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /booking
   * - **API ID Path**: carousel_slice.items[].booking_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  booking_url: prismic.KeyTextField;

  /**
   * Room Features (comma-separated) field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Schreibtisch, Safe, TV, WLAN
   * - **API ID Path**: carousel_slice.items[].room_features
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  room_features: prismic.KeyTextField;
}

/**
 * Default variation for CarouselSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default image carousel with full features
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceSliceDefaultPrimary>,
  Simplify<CarouselSliceSliceDefaultItem>
>;

/**
 * Primary content in *CarouselSlice → Minimal → Primary*
 */
export interface CarouselSliceSliceMinimalPrimary {
  /**
   * Section Heading field in *CarouselSlice → Minimal → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter section heading...
   * - **API ID Path**: carousel_slice.minimal.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Section Description field in *CarouselSlice → Minimal → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description...
   * - **API ID Path**: carousel_slice.minimal.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Aspect Ratio field in *CarouselSlice → Minimal → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose aspect ratio
   * - **Default Value**: 16/9
   * - **API ID Path**: carousel_slice.minimal.primary.aspect_ratio
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  aspect_ratio: prismic.SelectField<
    "16/9" | "21/9" | "4/3" | "3/2" | "1/1",
    "filled"
  >;

  /**
   * Autoplay field in *CarouselSlice → Minimal → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carousel_slice.minimal.primary.autoplay
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  autoplay: prismic.BooleanField;

  /**
   * Autoplay Interval (ms) field in *CarouselSlice → Minimal → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 5000
   * - **API ID Path**: carousel_slice.minimal.primary.autoplay_interval
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  autoplay_interval: prismic.NumberField;

  /**
   * Show Preview Thumbnails field in *CarouselSlice → Minimal → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carousel_slice.minimal.primary.show_thumbnails
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_thumbnails: prismic.BooleanField;

  /**
   * Show Dot Indicators field in *CarouselSlice → Minimal → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carousel_slice.minimal.primary.show_indicators
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_indicators: prismic.BooleanField;

  /**
   * Show Navigation Arrows field in *CarouselSlice → Minimal → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: carousel_slice.minimal.primary.show_navigation
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_navigation: prismic.BooleanField;
}

/**
 * Primary content in *CarouselSlice → Items*
 */
export interface CarouselSliceSliceMinimalItem {
  /**
   * Carousel Image field in *CarouselSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<"carousel_thumb">;

  /**
   * Image Caption field in *CarouselSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter image caption...
   * - **API ID Path**: carousel_slice.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Room Title field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Einzelzimmer
   * - **API ID Path**: carousel_slice.items[].room_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  room_title: prismic.KeyTextField;

  /**
   * Room Description field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Perfekt für Alleinreisende
   * - **API ID Path**: carousel_slice.items[].room_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  room_description: prismic.KeyTextField;

  /**
   * Bed Type field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Einzelbett mit Federkernmatratze
   * - **API ID Path**: carousel_slice.items[].room_bed_type
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  room_bed_type: prismic.KeyTextField;

  /**
   * Booking Button Text field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Jetzt Buchen
   * - **API ID Path**: carousel_slice.items[].booking_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  booking_button_text: prismic.KeyTextField;

  /**
   * Booking URL field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /booking
   * - **API ID Path**: carousel_slice.items[].booking_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  booking_url: prismic.KeyTextField;

  /**
   * Room Features (comma-separated) field in *CarouselSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Schreibtisch, Safe, TV, WLAN
   * - **API ID Path**: carousel_slice.items[].room_features
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  room_features: prismic.KeyTextField;
}

/**
 * Minimal variation for CarouselSlice Slice
 *
 * - **API ID**: `minimal`
 * - **Description**: Minimal carousel without thumbnails and indicators
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSliceSliceMinimal = prismic.SharedSliceVariation<
  "minimal",
  Simplify<CarouselSliceSliceMinimalPrimary>,
  Simplify<CarouselSliceSliceMinimalItem>
>;

/**
 * Slice variation for *CarouselSlice*
 */
type CarouselSliceSliceVariation =
  | CarouselSliceSliceDefault
  | CarouselSliceSliceMinimal;

/**
 * CarouselSlice Shared Slice
 *
 * - **API ID**: `carousel_slice`
 * - **Description**: Image carousel with preview thumbnails, navigation, and customizable settings
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSliceSlice = prismic.SharedSlice<
  "carousel_slice",
  CarouselSliceSliceVariation
>;

/**
 * Primary content in *FAQSlice → Default → Primary*
 */
export interface FaqSliceSliceDefaultPrimary {
  /**
   * Section Title field in *FAQSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Frequently Asked Questions
   * - **API ID Path**: faq_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Section Description field in *FAQSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Find answers to common questions about our hotel
   * - **API ID Path**: faq_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Show Category Filters field in *FAQSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: faq_slice.default.primary.show_categories
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_categories: prismic.BooleanField;
}

/**
 * Default variation for FAQSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FAQSlice*
 */
type FaqSliceSliceVariation = FaqSliceSliceDefault;

/**
 * FAQSlice Shared Slice
 *
 * - **API ID**: `faq_slice`
 * - **Description**: FAQ section with collapsible items and categorization
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceSlice = prismic.SharedSlice<
  "faq_slice",
  FaqSliceSliceVariation
>;

/**
 * Primary content in *FeatureSlice → Image Left → Primary*
 */
export interface FeatureSliceSliceImageLeftPrimary {
  /**
   * Heading field in *FeatureSlice → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Feature Heading
   * - **API ID Path**: feature_slice.imageLeft.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *FeatureSlice → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Feature Subheading
   * - **API ID Path**: feature_slice.imageLeft.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subheading: prismic.RichTextField;

  /**
   * Content field in *FeatureSlice → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Feature content text
   * - **API ID Path**: feature_slice.imageLeft.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Feature Image field in *FeatureSlice → Image Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_slice.imageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Alt Text field in *FeatureSlice → Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Describe the image
   * - **API ID Path**: feature_slice.imageLeft.primary.image_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_alt: prismic.KeyTextField;
}

/**
 * Image Left variation for FeatureSlice Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Image on the left, content on the right
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSliceSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<FeatureSliceSliceImageLeftPrimary>,
  never
>;

/**
 * Primary content in *FeatureSlice → Image Right → Primary*
 */
export interface FeatureSliceSliceImageRightPrimary {
  /**
   * Heading field in *FeatureSlice → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Feature Heading
   * - **API ID Path**: feature_slice.imageRight.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *FeatureSlice → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Feature Subheading
   * - **API ID Path**: feature_slice.imageRight.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subheading: prismic.RichTextField;

  /**
   * Content field in *FeatureSlice → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Feature content text
   * - **API ID Path**: feature_slice.imageRight.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Feature Image field in *FeatureSlice → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_slice.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Alt Text field in *FeatureSlice → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Describe the image
   * - **API ID Path**: feature_slice.imageRight.primary.image_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_alt: prismic.KeyTextField;
}

/**
 * Image Right variation for FeatureSlice Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Image on the right, content on the left
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSliceSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<FeatureSliceSliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *FeatureSlice*
 */
type FeatureSliceSliceVariation =
  | FeatureSliceSliceImageLeft
  | FeatureSliceSliceImageRight;

/**
 * FeatureSlice Shared Slice
 *
 * - **API ID**: `feature_slice`
 * - **Description**: Feature section with heading, subheading, text and image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSliceSlice = prismic.SharedSlice<
  "feature_slice",
  FeatureSliceSliceVariation
>;

/**
 * Primary content in *HeadingSlice → Default → Primary*
 */
export interface HeadingSliceSliceDefaultPrimary {
  /**
   * Title field in *HeadingSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Page Title
   * - **API ID Path**: heading_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HeadingSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Page subtitle or description
   * - **API ID Path**: heading_slice.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Text Alignment field in *HeadingSlice → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose text alignment
   * - **Default Value**: center
   * - **API ID Path**: heading_slice.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  alignment: prismic.SelectField<"center" | "left" | "right", "filled">;
}

/**
 * Default variation for HeadingSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadingSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadingSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeadingSlice*
 */
type HeadingSliceSliceVariation = HeadingSliceSliceDefault;

/**
 * HeadingSlice Shared Slice
 *
 * - **API ID**: `heading_slice`
 * - **Description**: Page heading with title and subtitle
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadingSliceSlice = prismic.SharedSlice<
  "heading_slice",
  HeadingSliceSliceVariation
>;

/**
 * Primary content in *HeroSlice → Default → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Title field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Hotel Ludwig van Beethoven
   * - **API ID Path**: hero_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Your luxury retreat in the heart of the city
   * - **API ID Path**: hero_slice.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Background Image field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Primary Button Text field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Book Your Stay
   * - **API ID Path**: hero_slice.default.primary.primary_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * Secondary Button Text field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Explore
   * - **API ID Path**: hero_slice.default.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * Booking URL field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://booking.example.com
   * - **API ID Path**: hero_slice.default.primary.booking_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  booking_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Show Booking Widget field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: hero_slice.default.primary.show_booking_widget
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_booking_widget: prismic.BooleanField;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: Hero section with title, subtitle, image and buttons
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

/**
 * Primary content in *ImageSlice → Default → Primary*
 */
export interface ImageSliceSliceDefaultPrimary {
  /**
   * Image field in *ImageSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slice.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *ImageSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Image caption...
   * - **API ID Path**: image_slice.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Layout field in *ImageSlice → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose layout
   * - **Default Value**: contained
   * - **API ID Path**: image_slice.default.primary.layout
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  layout: prismic.SelectField<"full-width" | "contained", "filled">;
}

/**
 * Default variation for ImageSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageSlice*
 */
type ImageSliceSliceVariation = ImageSliceSliceDefault;

/**
 * ImageSlice Shared Slice
 *
 * - **API ID**: `image_slice`
 * - **Description**: Image with optional caption and layout options
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceSlice = prismic.SharedSlice<
  "image_slice",
  ImageSliceSliceVariation
>;

/**
 * Primary content in *JobSlice → Default → Primary*
 */
export interface JobSliceSliceDefaultPrimary {
  /**
   * Section Title field in *JobSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Job Opportunities
   * - **API ID Path**: job_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Section Description field in *JobSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Join our team at Hotel Ludwig van Beethoven
   * - **API ID Path**: job_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Show Department Filters field in *JobSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: job_slice.default.primary.show_filters
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_filters: prismic.BooleanField;
}

/**
 * Default variation for JobSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JobSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JobSlice*
 */
type JobSliceSliceVariation = JobSliceSliceDefault;

/**
 * JobSlice Shared Slice
 *
 * - **API ID**: `job_slice`
 * - **Description**: Job listings display with filtering options
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobSliceSlice = prismic.SharedSlice<
  "job_slice",
  JobSliceSliceVariation
>;

/**
 * Primary content in *ReviewsSlice → Default → Primary*
 */
export interface ReviewsSliceSliceDefaultPrimary {
  /**
   * Title field in *ReviewsSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: What our guests say
   * - **API ID Path**: reviews_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ReviewsSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Highly rated across all major booking platforms...
   * - **API ID Path**: reviews_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *ReviewsSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Read All Reviews
   * - **API ID Path**: reviews_slice.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *ReviewsSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /reviews
   * - **API ID Path**: reviews_slice.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *ReviewsSlice → Items*
 */
export interface ReviewsSliceSliceDefaultItem {
  /**
   * Platform field in *ReviewsSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Google
   * - **API ID Path**: reviews_slice.items[].platform
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  platform: prismic.KeyTextField;

  /**
   * Score field in *ReviewsSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 4.3/5
   * - **API ID Path**: reviews_slice.items[].score
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  score: prismic.KeyTextField;
}

/**
 * Default variation for ReviewsSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsSliceSliceDefaultPrimary>,
  Simplify<ReviewsSliceSliceDefaultItem>
>;

/**
 * Slice variation for *ReviewsSlice*
 */
type ReviewsSliceSliceVariation = ReviewsSliceSliceDefault;

/**
 * ReviewsSlice Shared Slice
 *
 * - **API ID**: `reviews_slice`
 * - **Description**: Reviews section with ratings from multiple platforms
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsSliceSlice = prismic.SharedSlice<
  "reviews_slice",
  ReviewsSliceSliceVariation
>;

/**
 * Primary content in *RichTextSlice → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichTextSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Write your content here...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichTextSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichTextSlice*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichTextSlice Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: Rich text content with multiple paragraphs, headings, and lists
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactInfoDocument,
      ContactInfoDocumentData,
      FaqItemDocument,
      FaqItemDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      JobListingDocument,
      JobListingDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CarouselSliceSlice,
      CarouselSliceSliceDefaultPrimary,
      CarouselSliceSliceDefaultItem,
      CarouselSliceSliceMinimalPrimary,
      CarouselSliceSliceMinimalItem,
      CarouselSliceSliceVariation,
      CarouselSliceSliceDefault,
      CarouselSliceSliceMinimal,
      FaqSliceSlice,
      FaqSliceSliceDefaultPrimary,
      FaqSliceSliceVariation,
      FaqSliceSliceDefault,
      FeatureSliceSlice,
      FeatureSliceSliceImageLeftPrimary,
      FeatureSliceSliceImageRightPrimary,
      FeatureSliceSliceVariation,
      FeatureSliceSliceImageLeft,
      FeatureSliceSliceImageRight,
      HeadingSliceSlice,
      HeadingSliceSliceDefaultPrimary,
      HeadingSliceSliceVariation,
      HeadingSliceSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      ImageSliceSlice,
      ImageSliceSliceDefaultPrimary,
      ImageSliceSliceVariation,
      ImageSliceSliceDefault,
      JobSliceSlice,
      JobSliceSliceDefaultPrimary,
      JobSliceSliceVariation,
      JobSliceSliceDefault,
      ReviewsSliceSlice,
      ReviewsSliceSliceDefaultPrimary,
      ReviewsSliceSliceDefaultItem,
      ReviewsSliceSliceVariation,
      ReviewsSliceSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
